# Generated by Django 5.1.2 on 2025-05-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or instructions for this lab order', null=True),
        ),
    ]
