# Generated by Django 5.1.2 on 2025-05-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_create_work_areas'),
        ('hr', '0005_customuser_attendance_method'),
    ]

    operations = [
    ]
