# Generated by Django 5.1.2 on 2025-05-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_medication_default_dosage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfsettings',
            options={},
        ),
        migrations.RemoveField(
            model_name='pdfsettings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pdfsettings',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='pdfsettings',
            name='include_allergies',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pdfsettings',
            name='include_basic_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pdfsettings',
            name='include_complaint',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pdfsettings',
            name='include_diagnosis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pdfsettings',
            name='include_hospital_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pdfsettings',
            name='include_medical_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pdfsettings',
            name='include_physical_exam',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pdfsettings',
            name='font_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='pdfsettings',
            name='footer_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfsettings',
            name='header_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
